name: SSH via tmate

on:
  workflow_dispatch:

jobs:
  ssh-session:
    runs-on: ubuntu-24.04
    timeout-minutes: 0  # 🕒 tối đa 6 tiếng, giá trị lớn nhất được phép
    steps:
      - name: Start SSH session with tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
